name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permissions for gradlew if present
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Build Debug APK using Gradle wrapper if present, otherwise try gradle
        run: |
          if [ -f ./gradlew ]; then ./gradlew :app:assembleDebug --no-daemon; else gradle :app:assembleDebug --no-daemon; fi

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: StudentsPortfolioPro-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
